services:
  edcwebsite:
    build: .
    network_mode: host
    volumes:
      - ./website/db.sqlite3:/app/website/db.sqlite3
      - ./website/static:/app/website/static
      - ./website/media:/app/website/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings
    stdin_open: true
    tty: true
